# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true
    # Tell Symfony to trust the local machine as a proxy (Cloudflared runs locally)
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'

    # Tell Symfony to read the HTTPS and Host headers from Cloudflare
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
