# config/packages/menu.yaml
parameters:
    app_menu.sidebar:
        -
            title: Configuraciones
            icon: 'bi bi-gear-fill text-warning'
            roles: 'ROLE_ADMIN'
            children:
                -   title: Sistema
                    icon: 'bi bi-tools text-info'
                    children: # <-- This triggers the recursion
                        - { title: Usuarios Internos, route: app_user_internal_index, icon: 'bi bi-person-lines-fill text-info' }
                        - { title: Usuarios Externos, route: app_user_external_index, icon: 'bi bi-person-lines-fill text-info' }
                        - { title: Auditoria, route: app_auditoria_index, icon: 'bi bi-person-lines-fill text-info' }
                -   title: Alergias
                    icon: 'bi bi-virus text-success'
                    children: # <-- This triggers the recursion
                        - { title: Alergenos, route: app_alergenos_index, icon: 'bi bi-virus2 text-success' }
                        - { title: Reacciones, route: app_reacciones_index, icon: 'bi bi-virus2 text-success' }
                - { title: Discapacidades, route: app_discapacidades_index, icon: 'bi bi-person-wheelchair text-warning' }
                - { title: Condiciones, route: app_condiciones_index, icon: 'fa-solid fa-person-cane text-warning' }
                - { title: Inmunizaciones, route: app_inmunizaciones_index, icon: 'fa-solid fa-syringe text-warning' }
                - { title: Enfermedades, route: app_enfermedades_index, icon: 'fa-solid fa-head-side-cough text-warning' }
                - { title: Medicamentos, route: app_medicamentos_index, icon: 'bi bi-capsule-pill text-warning' }
        -
            title: Pacientes
            icon: 'bi bi-people-fill text-info'
            roles: 'ROLE_INTERNAL'
            children:
                - { title: Pacientes Registrados, route: app_paciente_index, icon: 'bi bi-person-badge-fill text-info' }
        -
            title: Citas
            icon: 'bi bi-calendar-plus-fill text-primary'
            roles: 'ROLE_INTERNAL'
            children:
                -   title: Configuraciones
                    icon: 'bi bi-gear text-warning'
                    roles: 'ROLE_ADMIN'
                    children:
                        - { title: Especialidades, route: app_especialidades_index, icon: 'bi bi-gear text-warning' }
                        - { title: Consultorios, route: app_consultorios_index, icon: 'bi bi-gear text-warning' }
                        - { title: Configurar Citas, route: app_citas_configuraciones_index, icon: 'bi bi-gear text-warning' }
                -   title: Todas las Citas
                    icon: 'bi bi-calendar-plus text-info'
                    children:
                        - { title: Filtrar Citas, route: app_citas_index_list, icon: 'bi bi-calendar-plus text-info' }
                -   title: Estadísticas
                    icon: 'bi bi-pie-chart-fill text-success'
                    roles: 'ROLE_ADMIN'
                    children:
                        - { title: Citas, route: app_citas_estadisticas_list, icon: 'bi bi-graph-down text-success' }
                        - { title: Especialidades, route: app_citas_estadisticas_especialidades, icon: 'bi bi-graph-down text-success' }
        -
            title: Mis Citas
            icon: 'bi bi-calendar-plus-fill text-primary'
            roles: 'ROLE_EXTERNAL'
            children:
                -   title: Citas Medicas
                    icon: 'bi bi-calendar-plus-fill text-primary'
                    children:
                        - { title: Solicitudes, route: app_citas_solicitudes_index, icon: 'bi bi-calendar-plus-fill text-primary' }
        -
            title: Consultas
            icon: 'bi bi-hospital-fill text-success'
            roles: 'ROLE_DOCTOR'
            children:
                - { title: Consultas Pendientes, route: app_consulta_pendientes_index, icon: 'bi bi-hospital text-warning', roles: 'ROLE_DOCTOR' }
                - { title: Consultas Activas, route: app_consulta_activas_index, icon: 'bi bi-hospital text-primary', roles: 'ROLE_DOCTOR' }
                - { title: Todas las Consultas, route: app_consulta_index, icon: 'bi bi-hospital text-success', roles: 'ROLE_DOCTOR' }
        -
            title: Emergencias
            icon: 'fa-solid fa-circle-h text-danger'
            roles: 'ROLE_ER'
            children:
                -   title: Configuraciones
                    icon: 'bi bi-gear text-warning'
                    children:
                        - { title: Zonas, route: app_zona_cama_index, icon: 'bi bi-gear text-warning' }
                        - { title: Camas, route: app_cama_index, icon: 'bi bi-gear text-warning' }
                -   title: Todas
                    icon: 'fa-solid fa-bed-pulse text-danger'
                    children:
                        - { title: Emergencias Actuales, route: app_emergencia_index, icon: 'fa-solid fa-bed-pulse text-danger' }
                        - { title: Historial de Emergencias, route: app_emergencia_listado, icon: 'fa-solid fa-magnifying-glass-plus text-danger' }
        -   title: Hospitalizaciones
            icon: 'fa-solid fa-bed text-info'
            roles: 'ROLE_INTERNAL'
            children:
                -   title: Configuraciones
                    icon: 'bi bi-gear text-warning'
                    children:
                        - { title: Areas, route: app_area_index, icon: 'bi bi-gear text-warning' }
                        - { title: Habitaciones, route: app_habitacion_index, icon: 'bi bi-gear text-warning' }
                        - { title: Camas, route: app_hospitalizacioncama_index, icon: 'bi bi-gear text-warning' }
                        - { title: Visitas, route: app_horario_visitas_index, icon: 'bi bi-gear text-warning' }
                -   title: Todas
                    icon: 'fa-solid fa-bed-pulse text-info'
                    children:
                        - { title: Pendientes, route: app_hospitalizacion_admisiones, icon: 'fa-solid fa-bed-pulse text-info' }
                        - { title: Actuales, route: app_hospitalizacion_censo, icon: 'fa-solid fa-bed-pulse text-info' }
                -   title: Visitas
                    icon: 'bi bi-calendar-fill text-success'
                    children:
                        - { title: Visitas, route: app_visita_hospitalaria_index, icon: 'bi bi-calendar-fill text-info' }
        -   title: Quirofano
            icon: 'fa-solid fa-circle-h text-warning'
            roles: 'ROLE_DOCTOR_QUIROFANO'
            children:
                -   title: Configuraciones
                    icon: 'bi bi-gear text-warning'
                    children:
                        - { title: Quirofano, route: app_quirofano_index, icon: 'bi bi-gear text-warning' }
                        - { title: Articulos, route: app_articulo_index, icon: 'bi bi-gear text-warning' }
                        - { title: Inventario, route: app_inventario_lote_index, icon: 'bi bi-gear text-warning' }
                -   title: Programacion
                    icon: 'fa-solid fa-bed-pulse text-info'
                    children:
                        - { title: Pizarra, route: app_cirugia_pizarra, icon: 'fa-solid fa-bed-pulse text-info' }
                        - { title: Agenda, route: app_cirugia_agenda, icon: 'fa-solid fa-bed-pulse text-info' }
